/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MarkerType = IDL.Variant({
  'danger' : IDL.Null,
  'safe' : IDL.Null,
  'waypoint' : IDL.Null,
});
export const MarkerId = IDL.Int;
export const Contact = IDL.Record({
  'relationship' : IDL.Text,
  'name' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Marker = IDL.Record({
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'title' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'markerType' : MarkerType,
});

export const idlService = IDL.Service({
  'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addMarker' : IDL.Func(
      [IDL.Float64, IDL.Float64, IDL.Text, MarkerType, IDL.Text],
      [MarkerId],
      [],
    ),
  'deleteContact' : IDL.Func([IDL.Text], [], []),
  'deleteMarker' : IDL.Func([MarkerId], [], []),
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getAllData' : IDL.Func(
      [],
      [
        IDL.Record({
          'contacts' : IDL.Vec(Contact),
          'markers' : IDL.Vec(Marker),
          'sosMessage' : IDL.Text,
        }),
      ],
      ['query'],
    ),
  'getAllMarkerIds' : IDL.Func([], [IDL.Vec(MarkerId)], ['query']),
  'getAllMarkers' : IDL.Func([], [IDL.Vec(Marker)], ['query']),
  'getContact' : IDL.Func([IDL.Text], [Contact], ['query']),
  'getMarker' : IDL.Func([MarkerId], [Marker], ['query']),
  'getMarkersByType' : IDL.Func([MarkerType], [IDL.Vec(Marker)], ['query']),
  'getSOSMessage' : IDL.Func([], [IDL.Text], ['query']),
  'updateContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateMarker' : IDL.Func(
      [MarkerId, IDL.Float64, IDL.Float64, IDL.Text, MarkerType, IDL.Text],
      [],
      [],
    ),
  'updateSOSMessage' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MarkerType = IDL.Variant({
    'danger' : IDL.Null,
    'safe' : IDL.Null,
    'waypoint' : IDL.Null,
  });
  const MarkerId = IDL.Int;
  const Contact = IDL.Record({
    'relationship' : IDL.Text,
    'name' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Marker = IDL.Record({
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'title' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'markerType' : MarkerType,
  });
  
  return IDL.Service({
    'addContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addMarker' : IDL.Func(
        [IDL.Float64, IDL.Float64, IDL.Text, MarkerType, IDL.Text],
        [MarkerId],
        [],
      ),
    'deleteContact' : IDL.Func([IDL.Text], [], []),
    'deleteMarker' : IDL.Func([MarkerId], [], []),
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getAllData' : IDL.Func(
        [],
        [
          IDL.Record({
            'contacts' : IDL.Vec(Contact),
            'markers' : IDL.Vec(Marker),
            'sosMessage' : IDL.Text,
          }),
        ],
        ['query'],
      ),
    'getAllMarkerIds' : IDL.Func([], [IDL.Vec(MarkerId)], ['query']),
    'getAllMarkers' : IDL.Func([], [IDL.Vec(Marker)], ['query']),
    'getContact' : IDL.Func([IDL.Text], [Contact], ['query']),
    'getMarker' : IDL.Func([MarkerId], [Marker], ['query']),
    'getMarkersByType' : IDL.Func([MarkerType], [IDL.Vec(Marker)], ['query']),
    'getSOSMessage' : IDL.Func([], [IDL.Text], ['query']),
    'updateContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateMarker' : IDL.Func(
        [MarkerId, IDL.Float64, IDL.Float64, IDL.Text, MarkerType, IDL.Text],
        [],
        [],
      ),
    'updateSOSMessage' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };