/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'relationship' : string,
  'name' : string,
  'phoneNumber' : string,
}
export interface Marker {
  'lat' : number,
  'lng' : number,
  'title' : string,
  'notes' : string,
  'timestamp' : bigint,
  'markerType' : MarkerType,
}
export type MarkerId = bigint;
export type MarkerType = { 'danger' : null } |
  { 'safe' : null } |
  { 'waypoint' : null };
export interface _SERVICE {
  'addContact' : ActorMethod<[string, string, string], undefined>,
  'addMarker' : ActorMethod<
    [number, number, string, MarkerType, string],
    MarkerId
  >,
  'deleteContact' : ActorMethod<[string], undefined>,
  'deleteMarker' : ActorMethod<[MarkerId], undefined>,
  'getAllContacts' : ActorMethod<[], Array<Contact>>,
  'getAllData' : ActorMethod<
    [],
    {
      'contacts' : Array<Contact>,
      'markers' : Array<Marker>,
      'sosMessage' : string,
    }
  >,
  'getAllMarkerIds' : ActorMethod<[], Array<MarkerId>>,
  'getAllMarkers' : ActorMethod<[], Array<Marker>>,
  'getContact' : ActorMethod<[string], Contact>,
  'getMarker' : ActorMethod<[MarkerId], Marker>,
  'getMarkersByType' : ActorMethod<[MarkerType], Array<Marker>>,
  'getSOSMessage' : ActorMethod<[], string>,
  'updateContact' : ActorMethod<[string, string, string], undefined>,
  'updateMarker' : ActorMethod<
    [MarkerId, number, number, string, MarkerType, string],
    undefined
  >,
  'updateSOSMessage' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];