/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Marker {
    lat: number;
    lng: number;
    title: string;
    notes: string;
    timestamp: bigint;
    markerType: MarkerType;
}
export type MarkerId = bigint;
export interface Contact {
    relationship: string;
    name: string;
    phoneNumber: string;
}
export enum MarkerType {
    danger = "danger",
    safe = "safe",
    waypoint = "waypoint"
}
export interface backendInterface {
    addContact(name: string, phoneNumber: string, relationship: string): Promise<void>;
    addMarker(lat: number, lng: number, title: string, markerType: MarkerType, notes: string): Promise<MarkerId>;
    deleteContact(name: string): Promise<void>;
    deleteMarker(id: MarkerId): Promise<void>;
    getAllContacts(): Promise<Array<Contact>>;
    getAllData(): Promise<{
        contacts: Array<Contact>;
        markers: Array<Marker>;
        sosMessage: string;
    }>;
    getAllMarkerIds(): Promise<Array<MarkerId>>;
    getAllMarkers(): Promise<Array<Marker>>;
    getContact(name: string): Promise<Contact>;
    getMarker(id: MarkerId): Promise<Marker>;
    getMarkersByType(markerType: MarkerType): Promise<Array<Marker>>;
    getSOSMessage(): Promise<string>;
    updateContact(name: string, newPhoneNumber: string, newRelationship: string): Promise<void>;
    updateMarker(id: MarkerId, lat: number, lng: number, title: string, markerType: MarkerType, notes: string): Promise<void>;
    updateSOSMessage(newMessage: string): Promise<void>;
}
import type { Contact as _Contact, Marker as _Marker, MarkerType as _MarkerType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addContact(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1, arg2);
            return result;
        }
    }
    async addMarker(arg0: number, arg1: number, arg2: string, arg3: MarkerType, arg4: string): Promise<MarkerId> {
        if (this.processError) {
            try {
                const result = await this.actor.addMarker(arg0, arg1, arg2, to_candid_MarkerType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMarker(arg0, arg1, arg2, to_candid_MarkerType_n1(this._uploadFile, this._downloadFile, arg3), arg4);
            return result;
        }
    }
    async deleteContact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteContact(arg0);
            return result;
        }
    }
    async deleteMarker(arg0: MarkerId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMarker(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMarker(arg0);
            return result;
        }
    }
    async getAllContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllContacts();
            return result;
        }
    }
    async getAllData(): Promise<{
        contacts: Array<Contact>;
        markers: Array<Marker>;
        sosMessage: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllData();
                return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllData();
            return from_candid_record_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMarkerIds(): Promise<Array<MarkerId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarkerIds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarkerIds();
            return result;
        }
    }
    async getAllMarkers(): Promise<Array<Marker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMarkers();
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMarkers();
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContact(arg0: string): Promise<Contact> {
        if (this.processError) {
            try {
                const result = await this.actor.getContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContact(arg0);
            return result;
        }
    }
    async getMarker(arg0: MarkerId): Promise<Marker> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarker(arg0);
                return from_candid_Marker_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarker(arg0);
            return from_candid_Marker_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMarkersByType(arg0: MarkerType): Promise<Array<Marker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMarkersByType(to_candid_MarkerType_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMarkersByType(to_candid_MarkerType_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSOSMessage(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getSOSMessage();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSOSMessage();
            return result;
        }
    }
    async updateContact(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContact(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContact(arg0, arg1, arg2);
            return result;
        }
    }
    async updateMarker(arg0: MarkerId, arg1: number, arg2: number, arg3: string, arg4: MarkerType, arg5: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMarker(arg0, arg1, arg2, arg3, to_candid_MarkerType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMarker(arg0, arg1, arg2, arg3, to_candid_MarkerType_n1(this._uploadFile, this._downloadFile, arg4), arg5);
            return result;
        }
    }
    async updateSOSMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSOSMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSOSMessage(arg0);
            return result;
        }
    }
}
function from_candid_MarkerType_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MarkerType): MarkerType {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Marker_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Marker): Marker {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    contacts: Array<_Contact>;
    markers: Array<_Marker>;
    sosMessage: string;
}): {
    contacts: Array<Contact>;
    markers: Array<Marker>;
    sosMessage: string;
} {
    return {
        contacts: value.contacts,
        markers: from_candid_vec_n4(_uploadFile, _downloadFile, value.markers),
        sosMessage: value.sosMessage
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lat: number;
    lng: number;
    title: string;
    notes: string;
    timestamp: bigint;
    markerType: _MarkerType;
}): {
    lat: number;
    lng: number;
    title: string;
    notes: string;
    timestamp: bigint;
    markerType: MarkerType;
} {
    return {
        lat: value.lat,
        lng: value.lng,
        title: value.title,
        notes: value.notes,
        timestamp: value.timestamp,
        markerType: from_candid_MarkerType_n7(_uploadFile, _downloadFile, value.markerType)
    };
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    danger: null;
} | {
    safe: null;
} | {
    waypoint: null;
}): MarkerType {
    return "danger" in value ? MarkerType.danger : "safe" in value ? MarkerType.safe : "waypoint" in value ? MarkerType.waypoint : value;
}
function from_candid_vec_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Marker>): Array<Marker> {
    return value.map((x)=>from_candid_Marker_n5(_uploadFile, _downloadFile, x));
}
function to_candid_MarkerType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarkerType): _MarkerType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MarkerType): {
    danger: null;
} | {
    safe: null;
} | {
    waypoint: null;
} {
    return value == MarkerType.danger ? {
        danger: null
    } : value == MarkerType.safe ? {
        safe: null
    } : value == MarkerType.waypoint ? {
        waypoint: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
